name = "crm-system-api"
main = "workers/index.ts"
compatibility_date = "2024-01-30"

[[d1_databases]]
binding = "DB"
database_name = "crm"
database_id = "64ce770d-53b8-4d98-aba4-287d0c05041d"  # You'll need to replace this with your actual D1 database ID
